### ISSUE TITLE
The repository doesn't have any code

### ISSUE THREAD

**Issue by JensRantil** [eripe970/gmp-test#2]
**Problem:** The repository doesn't have any code.

**Proposed solution:** Add some.

**Workaround:** Clone the repository and add some locally.

**Comment by eripe970** [comment]
Haha thanks! 

"The Best Code is No Code At All"

**Comment by JensRantil** [comment]
...or to [quote myself](http://www.quora.com/What-are-the-best-kept-secrets-of-great-programmers/answer/Jens-Rantil):

> Removing code is a great way to remove bugs.

**Comment by eripe970** [comment]
Nice list! :+1:
